version: "3.8"

services:
  nginx-rtmp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1935:1935
      - 8080:80
    volumes:
      - hls-shared:/tmp/hls
    restart: unless-stopped

volumes:
  hls-shared:
