apiVersion: apps/v1

kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    label: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: nginx-rtmp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 1935
              name: rtmp
            - containerPort: 80
              name: http