apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 1935
      name: rtmp
    - protocol: TCP
      port: 8080
      targetPort: 80
      name: http
  type: LoadBalancer